title: hdmetor's blog
email: hdmetor@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  hdmetor's programming and machine learning blog
baseurl: "/blog"

# Build settings
markdown: kramdown
theme: minima

google_analytics: UA-85316716-1
